version: "2"
services:
  web:
    image: avengersweb
    networks:
      - wheel
    ports:
      - "81:80"
  testcafe:
    image: testcafe/testcafe
    volumes:
      - ./Tests:/Tests
    command: "testcafe edge:headless /Tests/TestCafeTests.js -r junit:/reports/report.xml --skip-js-errors web"
    mem_limit: 200m
    links:
      - web:web
networks:
  wheel:
    driver: bridge
